version: '3.7'
services:
  slurm-sidecar:
    container_name: slurm-sidecar
    image: surax98/slurm-plugin:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    privileged: true
    cap_add:
    - SYS_ADMIN
    #network_mode: "host"
    ports:
    - 4000:4000
    volumes:
    - type: bind
      source: ../examples/config/SlurmConfig.yaml
      target: /root/SlurmConfig.yaml
    environment:
      - SLURMCONFIGPATH=/root/SlurmConfig.yaml
      - SHARED_FS=true
    # healthcheck:
    #   test: ["CMD", "/check.sh"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s