apiVersion: v1
kind: ConfigMap
metadata:
  name: "virtual-kubelet-config"
  namespace: interlink 
data:
  InterLinkConfig.yaml: |
    #InterlinkURL: unix:///var/run/interlink.socket
    InterlinkURL: "http://interlink"
    InterlinkPort: "3000" 
    ExportPodData: true
    VerboseLogging: true
    ErrorsOnlyLogging: false
    ServiceAccount: "virtual-kubelet"
    Namespace: interlink 
    VKTokenFile: ""
    CPU: "100"
    Memory: "128Gi"
    Pods: "100"
    HTTP:
      Insecure: true
    KubeletHTTP:
      Insecure: true

